depth_camera_intrinsic_params:
  dfx: 301.27933
  dfy: 301.27933
  dcx: 319.20093
  dcy: 235.68080

color_camera_intrinsic_params:
  fx: 396.65051
  fy: 396.72641
  cx: 329.94049
  cy: 233.1148
  Coeffs: [-0.36969, 0.16313, -0.00015, -0.00001, -0.037709]

depthPC2RGB_params:
  R_lidar2camera:
    - 0.99999
    - -0.00518
    - 0.00063
    - 0.00518
    - 0.99999
    - 0.00132
    - -0.00064
    - -0.00132
    - 1.00000
  T_lidar2camera:
    - -0
    - -1
    - -0
    - -0.03582
    - 1
    - 0
    - 0
    - -0.00005
    - 0
    - 0
    - 1
    - 0.00044
    - 0
    - 0
    - 0
    - 1
# path
depthImgPath: ~/rDepth/
rgbImgPath: ~/rColor/
ply_save_path: ~/ply/
colorPoints_save_path: ~/color-pc/
projectedRgb_save_path: ~/projected-img/
isDepthImg2PC: true
isDepthImg2ColorPC: true
isPcProject2Img: true


